### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Avizacherman** [graigjanssen/gjBoggle#1]
Graig,

Great job on this! It looks fantastic already and I agree with you that as you get more used to code you'll be able to implement the spellchecker. Think of it logically. If you are given a word by the user, and you have an array of words as a dictionary, how would you go about searching through your array for that word? 

As for shuffle, it looks like you grabbed a Fisher-Yates algorithm, which is the most common array shuffle algorithm. The idea is you go through a list, and for every item in the list, you swap the current index with a random index in the list. The `x` variable exists as a placeholder, because you need to temporarily store one of the values so it doesn't get lost. You can ready all about it here: https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle. 

Overall great work!

-Avi

**Comment by graigjanssen** [comment]
Thanks, Avi.  Glad I'm on the right track, and will definitely read up on
the Fisher Yates algorithm.

On Tue, Dec 1, 2015 at 12:06 PM, Avi Zacherman notifications@github.com
wrote:

> Graig,
> 
> Great job on this! It looks fantastic already and I agree with you that as
> you get more used to code you'll be able to implement the spellchecker.
> Think of it logically. If you are given a word by the user, and you have an
> array of words as a dictionary, how would you go about searching through
> your array for that word?
> 
> As for shuffle, it looks like you grabbed a Fisher-Yates algorithm, which
> is the most common array shuffle algorithm. The idea is you go through a
> list, and for every item in the list, you swap the current index with a
> random index in the list. The x variable exists as a placeholder, because
> you need to temporarily store one of the values so it doesn't get lost. You
> can ready all about it here:
> https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle.
> 
> Overall great work!
> 
> -Avi
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/graigjanssen/gjBoggle/issues/1.

## 

_Graig Janssen_
(856)-685-9008
www.graigjanssen.com

**Comment by ajhofferber** [comment]
Hey Graig,

I really like what you were able to come up with for you project! I think that boggle was a really interesting challenge for the project and I think you did a great job with it. I like that you have different levels of scoring and awards associated with each.  I can't wait to see what this would be like once you are able to implement a dictionary aspect. 

Overall, I think you did a great job breaking the game of boggle down into smaller pieces and taking steps to build them into your project. 

Score: 3 (refer to project markdown for score rubric)

-Ash
